# set up RDF properties according to your preferred metadata schema
schema:
    namespaces:
        id: https://id.acdh.oeaw.ac.at/
        vid: https://id.acdh.oeaw.ac.at/vid/
    versioning:
        isNewOf: https://vocabs.acdh.oeaw.ac.at/schema#isNewVersionOf
        isPrevOf: https://vocabs.acdh.oeaw.ac.at/schema#isPreviousVersionOf
    ingest:
        pid: https://vocabs.acdh.oeaw.ac.at/schema#hasPid
        location: https://vocabs.acdh.oeaw.ac.at/schema#hasLocationPath
        defaultBinaryClass: ''
        defaultCollectionClass: ''
    # ID normalization rules - see https://github.com/acdh-oeaw/uriNormalizer
    uriNorm: []
# client authorization
auth:
    httpBasic:
        user: ''
        passsword: ''
