name: build

on:
  push:
    paths:
    - docker/**

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build -t acdhch/arche-ingest --label "buildUrl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" .
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      run: docker push acdhch/arche-ingest

